import { useState, useEffect } from "react";
import { Loader2 } from "lucide-react";
import {
  useCreateInvoice,
  useUpdateInvoice,
  useInvoice,
  useLastInvoiceNotes,
  useContractUsage,
} from "./hooks";
import { toast } from "react-hot-toast";
import { useClientCompanies } from "../../features/clients/hooks";
import {
  useProjects,
  useProjectsByClientId,
} from "../../features/projects/hooks";
import { useProjectEmployees } from "../../features/project-employee/hooks";
import { useContracts } from "../../features/client-contracts/hooks";

import ParticularTable from "./ParticularTable";
import HourlyTable from "./HourlyTable";
import ConfirmDialog from "../../components/ui/ConfirmDialog";

type Item = {
  id: string;
  description: string;
  hsn_sac?: string;
  amount: number;
};

type HourlyItem = {
  id: string;
  employee_id?: string;
  role: string;
  role_name?: string;
  quantity: number;
  rate: number;
  hours: number;
};

export default function InvoiceCreate({
  invoiceId,
  cloneData,
  onSuccess,
}: {
  invoiceId?: string;
  cloneData?: any;
  onSuccess?: () => void;
}) {
  const createInvoice = useCreateInvoice();
  const updateInvoice = useUpdateInvoice();

  const isCloneParticular =
  cloneData && cloneData.billing_type === "PARTICULAR";

  const { data: invoiceData, isLoading: isInvoiceLoading } =
    useInvoice(invoiceId || "");

  // ================= STATE =================
  const [clientId, setClientId] = useState("");
  const [projectId, setProjectId] = useState("");

  // ✅ DEFAULT NO CONTRACT
  const [contractId, setContractId] = useState("");

  const [invoiceDate, setInvoiceDate] = useState("");
  const [notes, setNotes] = useState("");

  const [autoGenerateDate, setAutoGenerateDate] = useState("");

  const [showNoContractConfirm, setShowNoContractConfirm] =
    useState(false);

  const [pendingClientId, setPendingClientId] =
    useState<string | null>(null);
  const [pendingProjectId, setPendingProjectId] =
    useState<string | null>(null);
  const [pendingContractId, setPendingContractId] =
    useState<string | null>(null);

  const [confirmType, setConfirmType] = useState<
    "client" | "project" | "contract" | null
  >(null);

  const { data: clientData } = useClientCompanies(1, 50);
  const { data: allProjectData } = useProjects(1, 100);
  const { data: clientProjectData } =
    useProjectsByClientId(clientId);

  const { data: contractData } = useContracts(
    1,
    100,
    undefined,
    undefined,
    projectId
  );

  const clients = clientData?.client_companies ?? [];
  const selectedClient = clients.find(
    (c: any) => c.id === clientId
  );

  const currency = selectedClient?.billing_currency || "";

  const allProjects = allProjectData?.projects ?? [];
  const clientProjects = clientProjectData?.projects ?? [];
  const [prefilled, setPrefilled] = useState(false);

  const { data: usageData } =
    useContractUsage(contractId);

  const projects = [...allProjects, ...clientProjects].filter(
    (v, i, arr) =>
      arr.findIndex((x) => x.id === v.id) === i
  );

  const contracts = contractData?.contracts ?? [];

  const [billingType, setBillingType] = useState<
    "PARTICULAR" | "HOURLY"
  >("PARTICULAR");
  
  const isContextReady = !!clientId && !!projectId;

  const [items, setItems] = useState<Item[]>([]);
  const [hourlyItems, setHourlyItems] = useState<
    HourlyItem[]
  >([]);

  const { data: lastNotesData } =  useLastInvoiceNotes(projectId)
  const { data: assignedData } = useProjectEmployees(projectId);

  const [tax, setTax] = useState({
    cgstRate: 0,
    sgstRate: 0,
    igstRate: 0,
  });
  


  const [initialized, setInitialized] =
    useState(false);

  const selectedContract = contracts.find(
    (c: any) => c.id === contractId
  ); 
  
  const isRecurringContract =
  selectedContract?.type === "RECURRING";



useEffect(() => {
  if (!cloneData) return;

  // RESET FIRST
  setItems([]);
  setHourlyItems([]);

  setClientId(cloneData.client_id || "");
  setProjectId(cloneData.project_id || "");
  setContractId(cloneData.contract_id || "");

  setInvoiceDate(new Date().toISOString().split("T")[0]);

  setBillingType("PARTICULAR");

  if (cloneData.remaining > 0) {
    setItems([
      {
        id: crypto.randomUUID(),
        description: "Remaining Contract Amount",
        amount: Number(cloneData.remaining),
      },
    ]);
  }

  setPrefilled(true);
}, [cloneData]);

  // ================= PREFILL (EDIT MODE) =================
useEffect(() => {
  if (!invoiceData || prefilled) return;

  // ⛔ WAIT until projects are ready
  if (!projects.length) return;

  setClientId(invoiceData.client_id || "");
  setProjectId(invoiceData.project_id || "");
  setContractId(invoiceData.contract_id || "");
  setInvoiceDate(invoiceData.invoice_date || "");
  setNotes(invoiceData.notes || "");
  setAutoGenerateDate(invoiceData.auto_generate_date || "");

  const rawItems = invoiceData.items || [];

  const detectedType =
    rawItems.some((i: any) => i.billing_type === "HOURLY")
      ? "HOURLY"
      : "PARTICULAR";

  setBillingType(detectedType);

  if (detectedType === "PARTICULAR") {
    setItems(
      rawItems.map((i: any) => ({
        id: crypto.randomUUID(),
        description: i.description || "",
        hsn_sac: i.hsn_sac || "",
        amount: Number(i.amount) || 0,
      }))
    );
    setHourlyItems([]);
  }

  if (detectedType === "HOURLY") {
    setHourlyItems(
      rawItems.map((i: any) => ({
        id: crypto.randomUUID(),
        employee_id: i.employee_id || "",
        role: i.description || "",
        role_name: i.role_name || i.description || "",
        quantity: Number(i.quantity) || 1,
        rate: Number(i.rate) || 0,
        hours: Number(i.hours) || 0,
      }))
    );
    setItems([]);
  }

  const subtotal = invoiceData.subtotal || 1;

  setTax({
    cgstRate: ((invoiceData.cgst || 0) / subtotal) * 100,
    sgstRate: ((invoiceData.sgst || 0) / subtotal) * 100,
    igstRate: ((invoiceData.igst || 0) / subtotal) * 100,
  });

  setPrefilled(true);
}, [invoiceData, prefilled, projects.length]);


useEffect(() => {
  if (
    !invoiceId &&        // ✅ only for create (not edit)
    !cloneData &&        // ✅ not for clone
    !notes &&            // ✅ don’t overwrite user input
    lastNotesData?.notes // ✅ data exists
  ) {
    setNotes(lastNotesData.notes);
  }
}, [lastNotesData]);

    // ================= TOTAL =================
const subtotal =
  billingType === "PARTICULAR"
    ? items.reduce(
        (s, i) => s + (Number(i.amount) || 0),
        0
      )
    : hourlyItems.reduce(
        (s, i) =>
          s + i.quantity * i.rate * i.hours,
        0
      );

  const cgstAmount = (subtotal * tax.cgstRate) / 100;
  const sgstAmount = (subtotal * tax.sgstRate) / 100;
  const igstAmount = (subtotal * tax.igstRate) / 100;

  const total =
    subtotal + cgstAmount + sgstAmount + igstAmount;


const contractValue =
  selectedContract?.type === "FIXED"
    ? Number(selectedContract?.total_value || 0)
    : Number(selectedContract?.recurring_value || 0);

const usedAmount = usageData?.used || 0;

// 🔥 CRITICAL FIX (edit mode)
const adjustedUsed =
  invoiceId && invoiceData
    ? usedAmount - Number(invoiceData.total || 0)
    : usedAmount;

const currentInvoiceTotal = Number(total || 0);

// 🔥 FINAL REMAINING
const remaining =
  selectedContract?.type === "FIXED"
    ? contractValue - (adjustedUsed + currentInvoiceTotal)
    : null;

const exceedsRecurringLimit =
  isRecurringContract &&
  Number(total || 0) >
    Number(selectedContract?.recurring_value || 0);

  // ================= VALIDATION =================
const isValid =
  invoiceDate &&
  projectId &&
  total > 0 && // ✅ ADD THIS
  !exceedsRecurringLimit &&
  (
    (billingType === "PARTICULAR" && items.length > 0) ||
    (billingType === "HOURLY" && hourlyItems.length > 0)
  );

  const nextMonthMinDate = (() => {
  const d = new Date();
  d.setMonth(d.getMonth() + 1);
  d.setDate(1); // optional → start from 1st of next month
  return d.toISOString().split("T")[0];
  })();

  // ================= FINAL SUBMIT =================
  const submitFinal = async () => {
    const body = {
      client_id: clientId,
      project_id: projectId,
      contract_id: contractId || null,
      date: invoiceDate,
      billing_type: billingType,
      auto_generate_date: autoGenerateDate || null,
      items:
        billingType === "PARTICULAR"
          ? items
          : hourlyItems.map((i) => ({
              description: i.role,
              employee_id: i.employee_id,
              role_name: i.role_name,
              quantity: i.quantity,
              rate: i.rate,
              hours: i.hours,
              amount:
                i.quantity * i.rate * i.hours,
            })),
      subtotal,
      tax: {
        cgst: cgstAmount,
        sgst: sgstAmount,
        igst: igstAmount,
      },
      total,
      notes,
    };

    try {
      if (invoiceId) {
        await updateInvoice.mutateAsync({
          invoiceId,
          body,
        });
        toast.success("Invoice updated");
      } else {
        await createInvoice.mutateAsync(body);
        toast.success("Invoice created");
        onSuccess?.();
      }
    } catch {
      toast.error("Failed to save invoice");
    }
  };

  const handleSubmit = async () => {
    if (!clientId) return toast.error("Client required");
    if (!projectId) return toast.error("Project required");
    if (!invoiceDate) return toast.error("Date required");
    if (total <= 0) {
      return toast.error("Total must be greater than 0");
    }
    if (exceedsRecurringLimit) {
      return toast.error(
        `Total cannot exceed recurring contract value (${currency} ${Number(selectedContract?.recurring_value || 0).toFixed(2)})`
      );
     } 
    if (
      billingType === "PARTICULAR" &&
      items.length === 0
    ) {
      return toast.error("Add at least one item");
    }

    if (
      billingType === "HOURLY" &&
      hourlyItems.length === 0
    ) {
      return toast.error("Add at least one row");
    }

    // ✅ CONFIRM NO CONTRACT
   if (!contractId){
      setShowNoContractConfirm(true);
      return;
    }

    submitFinal();
  };

  const isLoading =
    createInvoice.isPending ||
    updateInvoice.isPending ||
    isInvoiceLoading;

  const isSubmitDisabled = isLoading || !isValid; 
 

  return (
    <div className="p-6 space-y-6">
      <h1 className="text-2xl font-bold">
        {invoiceId ? "Edit Invoice" : "Create Invoice"}
      </h1>

      <div className="grid md:grid-cols-4 gap-4">
        <select
          className="input"
          value={clientId}
          onChange={(e) =>
            setClientId(e.target.value)
          }
        >
          <option value="">Select Client</option>
          {clients.map((c: any) => (
            <option key={c.id} value={c.id}>
              {c.name}
            </option>
          ))}
        </select>

        <select
          className="input"
          value={projectId}
          disabled={!clientId}
          onChange={(e) =>
            setProjectId(e.target.value)
          }
        >
          <option value="">
            {clientId
              ? "Select Project"
              : "Select client first"}
          </option>
          {projects.map((p: any) => (
            <option key={p.id} value={p.id}>
              {p.name}
            </option>
          ))}
        </select>

        {/* ✅ CONTRACT */}
        <select
          className="input"
          value={contractId}
          disabled={!projectId}
          onChange={(e) =>
            setContractId(e.target.value)
          }
        >
          <option value="">
            No Contract
          </option>

          {contracts.map((c: any) => (
          <option key={c.id} value={c.id}>
            {c.contract_code || c.title} 
            {c.type === "FIXED" ? " (Fixed)" : " (Recurring)"}
          </option>
          ))}
        </select>

        <input
          type="date"
          className="input"
          value={invoiceDate}
          onChange={(e) =>
            setInvoiceDate(e.target.value)
          }
        />
      </div>
      <div className="flex gap-3">

<div className="flex gap-3">

  <button
    onClick={() => {
      if (invoiceId) return;
      setBillingType("PARTICULAR");
    }}
    disabled={
      !isContextReady ||
      (!!invoiceId && billingType === "HOURLY") ||
      isCloneParticular
    }
    className={`px-4 py-2 rounded ${
      billingType === "PARTICULAR"
        ? "bg-black text-white"
        : "bg-gray-200"
    } ${
      isCloneParticular
        ? "opacity-50 cursor-not-allowed"
        : ""
    }`}
  >
    Particular
  </button>

  <button
    onClick={() => {
      if (invoiceId) return;
      setBillingType("HOURLY");
    }}
    disabled={
      !isContextReady ||
      (!!invoiceId && billingType === "PARTICULAR") ||
      isCloneParticular
    }
    className={`px-4 py-2 rounded ${
      billingType === "HOURLY"
        ? "bg-black text-white"
        : "bg-gray-200"
    } ${
      isCloneParticular
        ? "opacity-50 cursor-not-allowed"
        : ""
    }`}
  >
    Hourly
  </button>

</div>

</div>

      {billingType === "PARTICULAR" ? (
      <ParticularTable
        items={items}
        setItems={setItems}
        disabled={!isContextReady}
      />
      ) : (
    <HourlyTable
      items={hourlyItems}
      setItems={setHourlyItems}
      assignedEmployees={assignedData?.employees || []}
      projectId={projectId}
      currency={currency}
      isEdit={!!invoiceId}
      disabled={!isContextReady}

    />
      )}



<div className="mt-4">
  <label className="text-sm font-medium text-gray-600">
    Notes
  </label>

  <textarea
    value={notes}
    onChange={(e) => setNotes(e.target.value)}
    placeholder="Add invoice notes (optional)..."
    className="w-full mt-1 p-3 border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
    rows={3}
    disabled={!isContextReady}
  />
</div>
{selectedContract?.type === "RECURRING" && (
 <div className="mt-4  max-w-sm">
  <div className="flex items-center gap-2">
    <label className="text-sm font-medium text-gray-600">
      Auto Invoice Generation Date
    </label> 
  </div> 
<input
  type="date"
  value={autoGenerateDate}
  min={nextMonthMinDate}
  onChange={(e) => setAutoGenerateDate(e.target.value)}
  className="w-full mt-1 p-3 border rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-indigo-500"
  disabled={!isContextReady}
/>

  <p className="text-xs text-gray-500 mt-1">
    Runs every month on the selected date
  </p>
</div>
)}  
<div className="text-right space-y-1">
  <div className="font-bold text-lg">
    Total: {currency} {total.toFixed(2)}
  </div>
  {isRecurringContract && (
  <div className="text-sm text-blue-600 font-medium">
    Recurring Limit: {currency}{" "}
    {Number(selectedContract?.recurring_value || 0).toFixed(2)}
  </div>
)}
  {exceedsRecurringLimit && (
  <div className="text-sm text-red-600 font-medium">
    Total exceeds recurring limit ({currency} {Number(selectedContract?.recurring_value || 0).toFixed(2)})
  </div>
  )}

  {selectedContract?.type === "FIXED" && remaining !== null && (
    <div
      className={`text-sm font-medium ${
        remaining < 0 ? "text-red-600" : "text-green-600"
      }`}
    >
      Remaining: {currency} {remaining.toFixed(2)}
    </div>
  )}
</div>

<button
  onClick={handleSubmit}
  disabled={isSubmitDisabled}
  className={`px-6 py-3 rounded-xl flex items-center justify-center gap-2 text-white min-w-[160px]
    ${isSubmitDisabled
      ? "bg-gray-400 cursor-not-allowed"
      : "bg-indigo-600 hover:bg-indigo-700"
    }`}
>
  <span className="flex items-center gap-2">
    {isLoading && (
      <Loader2 className="w-4 h-4 animate-spin" />
    )}
    {invoiceId ? "Update Invoice" : "Save Invoice"}
  </span>
</button>

      {/* ✅ NO CONTRACT CONFIRM */}
      <ConfirmDialog
        open={showNoContractConfirm}
        title="Proceed without contract?"
        description="This invoice will not be linked to any contract."
        confirmLabel="Yes, Continue"
        danger
        onConfirm={() => {
          setShowNoContractConfirm(false);
          submitFinal();
        }}
        onClose={() =>
          setShowNoContractConfirm(false)
        }
      />
    </div>
  );
}